---
# These variables can be overridden in distribution files.

# Dependencies required to install Buildbot
buildbot_deps:
  - python-pip # So we can install Python modules

# Dependencies required to download files
fetch_deps:
  - curl # For depends/
  - git
  - wget # For zcutil/fetch-params.sh

# Dependencies required to configure Vcoin
conf_deps:
  - autoconf
  - automake
  - m4
  - pkg-config

# Dependencies required to compile Vcoin
build_deps:
  - cmake
  - g++
  - gcc
  - make

# Dependencies required to link Vcoin
link_deps:
  - libtool

# Additional distribution-specific dependencies
dist_deps: []

# Additional grind-specific dependencies
grind_deps:
  - lcov
  - valgrind

# Python modules required on the system
system_modules:
  - virtualenv

# Python modules required for a Vcoin Buildbot worker+
buildbot_modules:
  - pip # Needs to be updated first so Buildbot installs
  - buildbot-worker
  - pyflakes

# Python modules required to run the Vcoin RPC test suite
rpc_test_modules:
  - pyblake2
  - pyzmq
